services:
  backend:
    image: guiifurlan/65pin-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pin3
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

  frontend:
    image: guiifurlan/65pin-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: guiifurlan/65pin3-db
    environment:
      POSTGRES_DB: pin3
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
